### ISSUE TITLE
Unexpected message arrived for topics without leading /

### ISSUE THREAD

**Issue by sgofferj** [4refr0nt/iot-manager-demo#15]
When using a topic prefix without a leading "/", e.g. "IoTmanager" instead of "/IoTmanager", nothing happens on the dashboard and the log shows "Unexpected message arrived".

It is allowed to use a leading forward slash in MQTT, for example /myhome/groundfloor/livingroom. But that introduces a unnecessary topic level with a zero character at the front. That should be avoided, because it doesn’t provide any benefit and often leads to confusion. (http://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices)

**Comment by 4refr0nt** [comment]
Prefix issue fixed in 2.1.0 version
