### ISSUE TITLE
intermediary, LED strip, toggle

### ISSUE THREAD

**Issue by v4rt** [4refr0nt/iot-manager-demo#16]
good afternoon.
I do not know if I need to write, I'm trying to make a smart house, I've set everything up to work with your application, and I have comments on the offer.
1. I noticed not convenience in the fact that the manager had to re-query the device list, in consequence of which the device is hung up suspend, (I have 20 relays on one device), it is probably worth to add an intermediary to transfer information about widgets. To unload the end devices.
2. it would be great to have a widget for selecting the color of the RGB LED strip
3. Widgets do not show the current status of the switches when updating the list (here perhaps I myself have missed something), and do not change the state if there was an external change, i.e. A light switch was clicked.

**Comment by 4refr0nt** [comment]
Try widget toggle in new version 2.1.0
