### ISSUE TITLE
IOT Manager and ios 11

### ISSUE THREAD

**Issue by Murrayc2000** [4refr0nt/iot-manager-demo#19]
Can you confirm if IOT manager works with ios 11 on iPhone. I have just upgraded my iPhone to ios 11 and it now will not connect to the broker (CloudMQTT using MQTT Websockets).

Thanks,

Murray

**Comment by Murrayc2000** [comment]
I tried deleting the app and reinstalling it again, but now I also have the same issue as the previous user, I cannot find the app on the apple store?

Regards,

Murray

**Comment by 4refr0nt** [comment]
Hi!
I can't test with iOS 11 because by Apple dev account expired.

**Comment by 4refr0nt** [comment]
IoTManager 2.1.0 version support all iOS versions from 8.0
