### ISSUE TITLE
Changing prefix (/IoTmanager by default) is not loded to dasboard

### ISSUE THREAD

**Issue by ghost** [4refr0nt/iot-manager-demo#21]
If change prefix from /IoTmanager to /IoTmanager/m for example in settings of IoTmanager and in my app,
IoTmanager still use /IoTmanager/+/config instead of /IoTmanager/m/+/config for load configuration of dashboard. For msg with topic like  /IoTmanager/m/deviceID/config in logs I see "Unexpected message arrived "

**Comment by 4refr0nt** [comment]
You can use "one-level" prefix only, ex "/myhome" or "myhome". Its bug will be fixed in furture.

**Comment by 4refr0nt** [comment]
Try 2.1.0 version
