### ISSUE TITLE
IOS - not save settings (broker, port, pass, user...)

### ISSUE THREAD

**Issue by aminachev** [4refr0nt/iot-manager-demo#25]
Good evening!

I am using IOT manager on iphone 6, ios 11.

After closing of application I need to enter all connection settings one more time.
Is this an issue or I`m doing something wrong?

**Comment by aminachev** [comment]
Please, make label on main site http://iotmanager.ru/ that you not support IOS devices anymore, and open issues will not be fixed.

Your app is interesting, but I spent 2 days with writing scripts, and now I understand that I can`t use it because of this issue.

**Comment by 4refr0nt** [comment]
Try iOS version 2.1.0
