### ISSUE TITLE
Android app not found

### ISSUE THREAD

**Issue by furang** [4refr0nt/iot-manager-demo#27]
Hi!
I've noticed android app disappeared in google play store. I need it. Your app is the best among other MQTT dashboards. Can you please upload it anywhere?

**Comment by brasofilo** [comment]
If you search for "ru.esp8266.iotmanager" you'll find an APK from 2017, v1.55. I won't link it here because it's not clear why the app disappeared. I installed and seems pretty cool.

**Comment by 4refr0nt** [comment]
v2.0 https://play.google.com/store/apps/details?id=ru.esp8266.iotmanager
