### ISSUE TITLE
IotManager 2.0

### ISSUE THREAD

**Issue by tranpic** [4refr0nt/iot-manager-demo#28]
I get IotManager 2.0, thank you so much
But it can not use "widget": "range"
Thank you so much

**Comment by 4refr0nt** [comment]
Widget RANGE in TODO list now

**Comment by iranweld** [comment]
Hi Mr Victor

IoTmanger APP ver 2 for Android , not item for exit from software?

**Comment by 4refr0nt** [comment]
Exit button for Android will be at next release at Feb 2020 with range widget

**Comment by lastun** [comment]
Hello Victor,
After updated to new version of the App 2.0 on my android phone, the widgets for display values from sensor ADC , range, KEY are not shown. Only widget "toggle"(button on IoTmanager App) works.
I tested your example for filling gauge to check if my program work well and is the same problem.
Can you please advise me how to solve the issue?
Thank you in advance

**Comment by tranpic** [comment]
Hi all, 
IotManager v2 connect to broker is very slow. 
Can not read property 'CordovaMqTTPlugin' of undefine.

**Comment by 4refr0nt** [comment]
Hi, All!

@iranweld EXIT button released.

@lastun, IoT Manager 2.0 does not have several old widgets. But version 2.0.8 (published 02.02.2020) have `range` and new widgets `progress-round` and `progress-line`. Its version also have in app Widgets Collection, where you can see examples and view and send to email code for all widgets.

@tranpic, You can try WSS connection type (this use MQTTJS engine, not CordovaMqTTPlugin).

**Comment by tranpic** [comment]
Hi, Victor,
slide widget is auto return to 52%, so can not change value.

**Comment by 4refr0nt** [comment]
@tranpic Hi! You must publish new `status` from device, after receiving message from `control`, `range` widget worked as widget `toggle`. After receiving new `status` widget `range` move to new `status` position

**Comment by tranpic** [comment]
yes, i had publish new status with value from 0 to 1023. i will debug again, thank you so much

**Comment by 4refr0nt** [comment]
@tranpic, remember for mapping range from 0-1023 to 0-100 you must use `k:0.0977`  in config - see  [example](https://github.com/4refr0nt/iotmanager-heroku/blob/master/index.js#L236)

**Comment by BoarTopaz** [comment]
Здравия!
Приложение не работает на версиях Андроид 4.4.2.
Пробовал установить на разных планшетах и телефонах с версией Андроида ниже 6.0. Приложение устанавливается, запускается, выводится логотип, переходящий в бесконечный белый экран. Из приложения можно выйти.

**Comment by tranpic** [comment]
Hi Victor,
Can IoTmanager v2 vibrate ??? 
I set vibrate: 50 in status bus have not vibrate.
Thank

**Comment by 4refr0nt** [comment]
@tranpic Hi! Vibrate worked now in v2.1.0 for Android and iOS
