### ISSUE TITLE
Using DHT and other sensors.

### ISSUE THREAD

**Issue by smead1** [4refr0nt/iot-manager-demo#3]
Hi, I'm working on a project to get sensors data from esp8266 and show them on IOT manager and control some relays... I've connected esp8266 to the broker and I used some examples (IDE) like Iotmanager 2 & 3 .ino and it worked. But my problem is that, I can't creat widget to do what I need like showing temp and hum and others , I really don't understand Widgets on Iot manager! Please help me.
I want to show 2 little fillgauge widget on top of the page to show up water level and Hum level, under that temperature and water temperature (DS18B20) and ADC using anydata.
Bottom of the page controling relays. My problem is only showing widgets
Sry for my english. Thanks

**Comment by 4refr0nt** [comment]
Hi!
For more easy learnign IoT Manager try Platformio example https://github.com/4refr0nt/iot-manager-demo/tree/master/platformio/heater
Widgets can be simplest configured by files https://github.com/4refr0nt/iot-manager-demo/tree/master/platformio/heater/prebuild/json
Also, you can read Widgets Guide at [http://iotmanager.ru](http://iotmanager.ru/)

**Comment by smead1** [comment]
Not working... :(
I add other widgets to "iotmanager2.ino" example but not showing in app!
Could you please just add 2 fillgauge widgets and anydata to that example?

**Comment by 4refr0nt** [comment]
Yes, I can, but now I'm busy on another project. Please, send me email reminder after one week.

**Comment by smead1** [comment]
Ok thanks.

**Comment by smead1** [comment]
I've sent a gmail for you.

**Comment by smead1** [comment]
Are you busy?
Anyother person can help me?!

**Comment by 4refr0nt** [comment]
Try new version 2.1.0
