### ISSUE TITLE
change toggle 

### ISSUE THREAD

**Issue by iranweld** [4refr0nt/iot-manager-demo#30]
in Iotmanager ver 2 when change toggle position to On , without resive {status:1}
show toggle ON in App

![Screenshot_20200123-070930](https://user-images.githubusercontent.com/4194016/72960128-f1a00500-3dc1-11ea-804c-7624333a4a8d.png)

**Comment by 4refr0nt** [comment]
Thanks!
Bug fixed,  new version 2.0.6 pending to Google Play (please, waiting for cache update)
Please, reopen issue, if you have troubles with toggle in 2.0.6 version.
