### ISSUE TITLE
iOS MQTT Protocol Missing

### ISSUE THREAD

**Issue by bgphoenix** [4refr0nt/iot-manager-demo#35]
Device: iPhone 12 | iOS14.6 | iOS15
Issue: When adding a new broker only WSS protocol is available, no MQTT (See attached screenshot) 

Tried reinstalling and installing on another iPhone. 

![image](https://user-images.githubusercontent.com/83557728/124898471-d8facd80-dffc-11eb-9505-e162c091c5e1.png)

**Comment by 4refr0nt** [comment]
Yes. Only WSS available in iOS version of app.
