### ISSUE TITLE
Radio button 

### ISSUE THREAD

**Issue by Torteski** [4refr0nt/iot-manager-demo#6]
Hi 4refr0nt
First thank you for IoT-Manager. It is a excellent system.
Secondly i was wondering if it is possible to use simple-btn as a radio button.
something like:
![image](https://cloud.githubusercontent.com/assets/24936820/21940198/83d13bda-d9c3-11e6-89c3-d194406543ca.png)

They would all be publishing to the same topic and it is not nessesery to be subscribed to anything.
So i imagin something like a radio button group.
Is this supported?

**Comment by 4refr0nt** [comment]
Input and select implements in 2.1.0 version
