### ISSUE TITLE
ESP8266 examples will not compile

### ISSUE THREAD

**Issue by SRFurst** [4refr0nt/iot-manager-demo#8]
The IDE examples for ESP8266 (IoTManager.ino and IoTManager2.ino) will no longer compile under Arduino IDE 1.8.1 and PubSub 2.6. It would appear that the syntax of the callback function has changed and this definition is no longer valid:

void callback(const MQTT::Publish& sub)

Can you update the examples, please?

**Comment by 4refr0nt** [comment]
IoT Manager examples incompatible with standart PubSub (any version). You must use PubSub from Imroy v1.91.1 from https://github.com/Imroy/pubsubclient (you can intstall it manually, without LibManager)
Its requrements publish in any examples in [header section](https://github.com/4refr0nt/iot-manager-demo/blob/master/ArduinoIDE/ESP8266/official-demo/AnydataToggle/AnydataToggle.ino#L12). Please, try compile with proper library.

**Comment by SRFurst** [comment]
Thank you, I did not know there were multiple forks of this library. Worked fine with the correct library!

 

On your widgets guide, you show 7 examples of Toggle widgets. Unfortunately, you only show the code for the first 6… It appears that the font size is increased on the 7th example and also that the icon has a color, whether the toggle is on or off. Can you share the code for that example, please?

 

 Thank you. I will leave a review on the iOS app store for you.

 

Sheldon
