### ISSUE TITLE
multiple esp8266 to same app

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [4refr0nt/iot-manager-demo#9]
I am not able to connect multiple esp8266 to same app

**Comment by 4refr0nt** [comment]
You must use different MQTT client names and [deviceID](https://github.com/4refr0nt/iot-manager-demo/blob/master/ArduinoIDE/ESP8266/official-demo/AnydataToggle/AnydataToggle.ino#L31) for several devices.
This is demo for 2 devices https://www.youtube.com/watch?v=-cbrn1lQGhM
